### ISSUE TITLE
Building on Linux (Debian) without Android support

### ISSUE THREAD

**Issue by a-rose** [google/lyra#10]
Hello,

When building on a Linux using the command given in README (`bazel build -c opt :encoder_main`), I get the following errors:

```
ERROR: /usr/local/src/lyra/WORKSPACE:121:1: name 'android_sdk_repository' is not defined
ERROR: /usr/local/src/lyra/WORKSPACE:128:1: name 'android_ndk_repository' is not defined
```

If I remove the lines related to `android_sdk_repository` and `android_sdk_repository` from the WORKSPACE file, I can build the encoder without issues.

I would like to find the correct way to deal with this and create a PR, but I don't know bazel, so I didn't find a way to ignore Android targets when building for Linux. Hopefully someone can fix it or point me to the right direction :)

edit: I'm using Debian in Docker, if that's any help:

```
FROM debian:bullseye-slim

WORKDIR /usr/local/src

RUN mkdir -p /usr/share/man/man1 \
    && apt-get update \
    && apt-get install -y \
        ninja-build git cmake clang python bazel-bootstrap

RUN git clone https://github.com/llvm/llvm-project.git \
    && cd llvm-project \
    && git checkout 96ef4f307df2 \
    && mkdir build_clang \
    && cd build_clang \
    && cmake -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DLLVM_ENABLE_PROJECTS="clang" -DCMAKE_BUILD_TYPE=release ../llvm \
    && ninja \
    && $(which ninja) install \
    && cd .. \
    && mkdir build_libcxx \
    && cd build_libcxx \
    && cmake -G Ninja -DCMAKE_C_COMPILER=/usr/local/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/bin/clang++ -DLLVM_ENABLE_PROJECTS="libcxx;libcxxabi" -DCMAKE_BUILD_TYPE=release ../llvm \
    && ninja \
    && $(which ninja) install \
    && ldconfig

RUN git clone --depth 1 --branch v0.0.1 https://github.com/google/lyra \
    && cd lyra \
    && bazel build -c opt :encoder_main \
    && bazel build -c opt :decoder_main
```

**Comment by Siddhant-K-code** [comment]
Have you ran `./configure` and set up Android SDK integration through the script instead?

**Comment by a-rose** [comment]
Thanks for your help, but I don't intend to build for Android or install the SDK. I'm building for Linux only, and I don't think the Android SDK is needed to build a linux program ;)

**Comment by xnorpx** [comment]
I followed the instructions, built Linux on Ubuntu 20 fine.

**Comment by a-rose** [comment]
@xnorpx right, I'm using Debian (I edited my post to give details) but I don't think the issue is related. Do you have the Android SDK installed?

**Comment by xnorpx** [comment]
@a-rose no, clean Ubuntu 20 WSL2 environment. Installed Bazel and then followed the Linux instructions and did not install anything Android related.

( Comment was mostly to confirm that Linux does build outside of g. )

**Comment by a-rose** [comment]
Ok then, the issue is only with Debian (after all, the docs said only Ubuntu was tested).

I would still like to find a way to make it work with other distros to help the project :)

**Comment by mchinen** [comment]
Thanks for the detailed report.  I'm not sure, but if I had to guess it might be related to your bazel version if it is old enough that android_*_repository is not supported.
`bazel --version` gives me `bazel 4.0.0`.

**Comment by paulmenzel** [comment]
Seem to be [version 3.5.1 in Debian (bazel-bootstrap (3.5.1+ds-3))](https://packages.debian.org/bullseye/bazel-bootstrap).

**Comment by a-rose** [comment]
Confirmed to work with bazel v4.0.0 from https://github.com/bazelbuild/bazel/releases. Thanks everyone ! 

Updated Dockerfile:

```
FROM debian:bullseye-slim

WORKDIR /usr/local/src

ARG BAZEL_VERSION=4.0.0
ADD https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel_${BAZEL_VERSION}-linux-x86_64.deb bazel_${BAZEL_VERSION}-linux-x86_64.deb

RUN apt-get update \
    && apt-get install -y \
        ninja-build git cmake clang python g++ unzip zip zlib1g-dev \
    && dpkg -i bazel_${BAZEL_VERSION}-linux-x86_64.deb

RUN git clone https://github.com/llvm/llvm-project.git \
    && cd llvm-project \
    && git checkout 96ef4f307df2 \
    && mkdir build_clang \
    && cd build_clang \
    && cmake -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DLLVM_ENABLE_PROJECTS="clang" -DCMAKE_BUILD_TYPE=release ../llvm \
    && ninja \
    && $(which ninja) install \
    && cd .. \
    && mkdir build_libcxx \
    && cd build_libcxx \
    && cmake -G Ninja -DCMAKE_C_COMPILER=/usr/local/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/bin/clang++ -DLLVM_ENABLE_PROJECTS="libcxx;libcxxabi" -DCMAKE_BUILD_TYPE=release ../llvm \
    && ninja \
    && $(which ninja) install \
    && ldconfig

RUN git clone --depth 1 --branch v0.0.1 https://github.com/google/lyra
RUN cd lyra \
    && bazel build -c opt :encoder_main \
    && bazel build -c opt :decoder_main
```
