### ISSUE TITLE
Does Lyra v2 support SoundStream denoising?

### ISSUE THREAD

**Issue by jamesgrahammv** [google/lyra#100]
I'm interested to know f Lyra v2 supports any of the SoundStream audio enhancement / denoising features.

**Comment by aluebs** [comment]
Currently Lyra v2 does **not** support SoundStream denoising. But the team is looking into it for potential next version.

**Comment by NilanEkanayake** [comment]
Sorry to hijack, but do you know when the standalone soundstream package will be released?
