### ISSUE TITLE
How to build lyra for linux arm64？

### ISSUE THREAD

**Issue by XDongiang** [google/lyra#103]
I want to build lyra for linux arm64 platform, please give me a help.

**Comment by mchinen** [comment]
We haven't tried linux arm64 hosts before, but if you are building on a arm64 host, you may try just following the linux instructions in the README.  The default build should be for the native host.  If you try it, please report back with what happens.

**Comment by XDongiang** [comment]
Thank you , i use the linux instructions in the README, it works well !
