### ISSUE TITLE
Can't we directly encode pcm？

### ISSUE THREAD

**Issue by liuxunfei** [google/lyra#117]
Must I enter wav for encoding？

**Comment by Radiomix2000** [comment]
Does your tittle "Can't we directly encode pcm?" mean you want process audiostream's input samples in realtime?

**Comment by liuxunfei** [comment]
>Yes, there are such real-time scenarios

**Comment by Radiomix2000** [comment]
Ok, I'm interested in that too. I was inspired by Lyra voice quality vs bitrate, and would like to make transceiver prototype in Gnuradio, to transmit and receive Lyra encoded digital voice over air.
