### ISSUE TITLE
Clang version to build llvm

### ISSUE THREAD

**Issue by HyacinthJingjing** [google/lyra#20]
When i use Clang 3.9.1 to build LLVM 12.0, it failed.
llvm-project/llvm/include/llvm/ADT/DenseMap.h:550:37: error: no matching constructor for initialization of 'llvm::ValueEnumerator::MDRange'
llvm-project/llvm/include/llvm/ADT/DenseMap.h:201:12: error: no matching constructor for initialization of 'llvm::ValueEnumerator::MDRange'
llvm-project/llvm/lib/Bitcode/Writer/ValueEnumerator.cpp:811:11: error: no matching constructor for initialization of 'llvm::ValueEnumerator::MDRange'
Should i use which version of Clang to build llvm?

**Comment by aluebs** [comment]
The [README](https://github.com/google/lyra/blob/main/README.md) has instructions on how to build a custom clang. Do you still get the error after following those.

**Comment by HyacinthJingjing** [comment]
Yes, i have used the command "cmake -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DLLVM_ENABLE_PROJECTS="clang" -DCMAKE_BUILD_TYPE=release ../llvm".

**Comment by aluebs** [comment]
Did that work? And did you ninja installed clang afterwards?

**Comment by HyacinthJingjing** [comment]
It did not work. About ”-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++“, does it support other compiler(gcc or g++)?

**Comment by aluebs** [comment]
Currently only clang is supported, because the std implementations need to be the same as the ones used to build the .so library.

**Comment by mchinen** [comment]
The question seems to be what version of clang you can use to build a bootstrapped clang.  We have used clang 6.0 to 12.0 to build our clang toolchain.  I believe 3.9.1 is quite old circa 2016.  Most package managers have a more recent version that you could try (if in ubuntu/debian, do `apt update` before installing clang).  We haven't tried using gcc or other compilers, so to keep things simple I would try using a more recent clang.

**Comment by HyacinthJingjing** [comment]
When i use bazel to build the project, i encountered this error:
WARNING: /search/odin/zhuweifeng/.cache/bazel/_bazel_zhuweifeng/cbee13c87ab2f3c1be98316600f9f92e/external/com_google_audio_dsp/third_party/fft2d/BUILD:3:11: in linkstatic attribute of cc_library rule @com_google_audio_dsp//third_party/fft2d:fft2d: setting 'linkstatic=1' is recommended if there are no object files
INFO: Analyzed target //:encoder_main (53 packages loaded, 1576 targets configured).
INFO: Found 1 target...
ERROR: /search/odin/zhuweifeng/.cache/bazel/_bazel_zhuweifeng/cbee13c87ab2f3c1be98316600f9f92e/external/com_google_audio_dsp/audio/dsp/portable/BUILD:319:10: Compiling audio/dsp/portable/write_wav_file_generic.c failed: undeclared inclusion(s) in rule '@com_google_audio_dsp//audio/dsp/portable:write_wav_file_generic':
this rule is missing dependency declarations for the following files included by 'audio/dsp/portable/write_wav_file_generic.c':
  '/search/odin/zhuweifeng/bazel_/llvm-project/build_clang/lib/clang/12.0.0/include/stdint.h'
  '/search/odin/zhuweifeng/bazel_/llvm-project/build_clang/lib/clang/12.0.0/include/stddef.h'
  '/search/odin/zhuweifeng/bazel_/llvm-project/build_clang/lib/clang/12.0.0/include/stdarg.h'
Target //:encoder_main failed to build
INFO: Elapsed time: 55.377s, Critical Path: 13.00s
INFO: 223 processes: 72 internal, 151 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
Can you give me some suggestions?

**Comment by aluebs** [comment]
Did you install the custom clang version like explained in the [README](https://github.com/google/lyra/blob/main/README.md) file? Because it seems like it isn't finding the includes that should be under /usr/local/lib/clang/12.0.0/include. Maybe @mchinen has more insight on this particular error.

**Comment by aluebs** [comment]
The new [Lyra v0.0.2](https://github.com/google/lyra/releases/tag/v0.0.2) doesn't require any custom clang installation anymore.
