### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by chenyonghuang** [google/lyra#24]
![image](https://user-images.githubusercontent.com/42790475/114878044-6ed5f080-9e32-11eb-8f06-ec7fe10aedf1.png)
I encountered this error when compiling this project. Before compiling, I have installed other dependencies according to the instructions, and I have not encountered any problems, but when I execute this command (bazel build -c opt :encoder_main), an error occurs. Can you tell me the reason and how to fix it . I haven't used bazel before, so I don't know how to modify it, can you help me

**Comment by chenyonghuang** [comment]
Thank you very much for this work, I learned a lot from it

**Comment by chenyonghuang** [comment]
I know my problem, sorry, it's okay

**Comment by aluebs** [comment]
I am glad to hear you figure out the error :)
