### ISSUE TITLE
Is the model and code of open source the same as the one used in the Lyra Google AI blog？

### ISSUE THREAD

**Issue by 14061145** [google/lyra#26]
I built lyra from linux(Ubuntu  20.04) using bazel for  a linux target. Then, I ran the samples published in [the lyra blog](https://ai.googleblog.com/2021/02/lyra-new-very-low-bitrate-codec-for.html) through the encoder_main and decoder_main binaries compiled from the open-sourced lyra code (the v0.0.1 and the latest commit). However, the quality of the samples decoded from open source code is inferior to the quality of the samples advertised in the lyra blog.
Is the model and code of open source the same as the one used in the Lyra Google AI blog？Why is there such a big difference in sound quality？
Thank you.

**Comment by aluebs** [comment]
Thank you for bringing this up and sorry for the confusion. Please see my answer in #25.
