### ISSUE TITLE
fail to build lyra_android_example

### ISSUE THREAD

**Issue by aijianiula0601** [google/lyra#36]
I use the command " bazel build android_example:lyra_android_example --config=android_arm64 --copt=-DBENCHMARK" follow the README.md and got the error below:

`
WARNING: /private/var/tmp/_bazel_jiahong/91206591588ab49765e9be8ccee0dd3b/external/com_google_audio_dsp/third_party/fft2d/BUILD:3:11: in linkstatic attribute of cc_library rule @com_google_audio_dsp//third_party/fft2d:fft2d: setting 'linkstatic=1' is recommended if there are no object files
INFO: Analyzed target //android_example:lyra_android_example (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_jiahong/91206591588ab49765e9be8ccee0dd3b/external/androidsdk/BUILD.bazel:13:25: Middleman _middlemen/external_Sandroidsdk_Saapt2_Ubinary-runfiles failed: missing input file 'external/androidsdk/build-tools/29.0.3/aapt2', owner: '@androidsdk//:build-tools/29.0.3/aapt2'
Target //android_example:lyra_android_example failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /private/var/tmp/_bazel_jiahong/91206591588ab49765e9be8ccee0dd3b/external/androidsdk/BUILD.bazel:13:25 Middleman _middlemen/external_Sandroidsdk_Saapt2_Ubinary-runfiles failed: 1 input file(s) do not exist
INFO: Elapsed time: 5.936s, Critical Path: 5.68s
INFO: 14 processes: 6 internal, 8 darwin-sandbox.
FAILED: Build did NOT complete successfully
`

---------------------------------

system：Mac
I installed Android Studio and installed the android sdk 29 and ndk 21 for requirement. How do I solve it ？ Thanks !

**Comment by aluebs** [comment]
Currently we don't support building on Mac. Please see #7 for some work-around ideas.
Also, our example is built without Android studio.

**Comment by lilinxiong** [comment]
@aluebs Hi~ I think there is a better solution to this problem.
I changed it like this, 
1st. Modify WORKSPACE in:[WORKSPACE#L36-L40](https://github.com/google/lyra/blob/main/WORKSPACE#L36-L40):

```bazel
git_repository(
    name = "com_google_absl",
    remote = "https://github.com/abseil/abseil-cpp.git",
    tag = "20210324.2",
    # Remove after https://github.com/abseil/abseil-cpp/issues/326 is solved.
    patches = [
        "@//third_party:com_google_absl_f863b622fe13612433fdf43f76547d5edda0c93001.diff"
    ],
    patch_args = [
        "-p1",
    ]
)
```
2end. 
``` bash
mkdir third_party
cd third_party
touch BUILD
touch com_google_absl_f863b622fe13612433fdf43f76547d5edda0c93001.diff
```

The content in ``BUILD`` is:
```bazel
licenses(["notice"])  # Apache License 2.0

exports_files(["LICENSE"])

package(default_visibility = ["//visibility:public"])
```

The content in ``com_google_absl_f863b622fe13612433fdf43f76547d5edda0c93001.diff`` is:
```diff
diff --git a/absl/time/internal/cctz/BUILD.bazel b/absl/time/internal/cctz/BUILD.bazel
index 9fceffe..e7f9d01 100644
--- a/absl/time/internal/cctz/BUILD.bazel
+++ b/absl/time/internal/cctz/BUILD.bazel
@@ -69,8 +69,5 @@ cc_library(
         "include/cctz/zone_info_source.h",
     ],
     linkopts = select({
-        ":osx": [
-            "-framework Foundation",
-        ],
         ":ios": [
             "-framework Foundation",
         ],
```

(I learned from [mediapipe#WORKSPCE#L25-L40](https://github.com/google/mediapipe/blob/master/WORKSPACE#L25-L40)... (:

**Comment by aluebs** [comment]
Thank you @lilinxiong for sharing your solution. We just uploaded a new version of Lyra which has experimental support for Mac. If your solution helps to reduce some of the warnings or improves upon it in any way, please feel free to send us a pull request.

**Comment by lilinxiong** [comment]
@aluebs Hi, I have submitted a pr, but it seems like I don't have permission to run the [action#build](https://github.com/google/lyra/actions/runs/3173981733) ... can you help me ?

**Comment by aluebs** [comment]
Thank you for submitting the PR. I think @mchinen would be a better person to review your Mac fix.

**Comment by lilinxiong** [comment]
> Thank you for submitting the PR. I think @mchinen would be a better person to review your Mac fix.

Ok～ Thanks～
