### ISSUE TITLE
The conditioning_only decoder.

### ISSUE THREAD

**Issue by aijianiula0601** [google/lyra#39]
What's the mean of conditioning_only decoder? I checked the source code but still not understand the different between conditioning_only and model_only . Has any explanation with them.

**Comment by aluebs** [comment]
The architecture we are using is similar to [WaveRNN](https://arxiv.org/pdf/1802.08435.pdf), in the sense that it has 2 different networks. The conditioning network that runs once for every frame, upsampling the input conditioning features to the sample rate. And the model network that runs once for every sample, combining the output of the conditioning network with the state of the previous samples to generate the next sample in an autoregressive fashion. When benchmarking we report the time for each of these networks, as well as the combined total.

**Comment by aijianiula0601** [comment]
Thanks for your response. I want to know : 
The audio quality of conditioning_only decoder.  Which is better, conditioning_only or model_only ?  And which type of decoder in the guide of README.md when the command is "babel-bin/decoder_main  --model_path=wavegru" . How can I get the generate audio for conditioning_only decoder.

**Comment by aluebs** [comment]
Oh, sorry I wasn't clear. Lyra always uses conditioning and model networks. There is no way to generate audio with conditioning only. We only report the complexity of each network separately in the benchmark tool to have a finer grain understanding of the computational complexity of different networks.

**Comment by aijianiula0601** [comment]
I got it. thanks!
