### ISSUE TITLE
Looking for function definitions

### ISSUE THREAD

**Issue by motepc** [google/lyra#42]
I am not able to find few function definitions like -
GruWithARInput, SpMM_bias etc,
or for any other conv1D, GRU related computational function definitions.

I can see declarations in ".h" files, but not the definitions.

Are those definitions available in this repository,
or are the obj files being directly imported from other git repositories?

Where can I see code for those functions?

Thanks for support.

**Comment by aluebs** [comment]
Those functions are part of the [sparse_inference_matrixvector](https://github.com/google/lyra/blob/main/BUILD#L844) library that was released as a dynamic (".so") binary, so the functions' code isn't available at this time.

**Comment by motepc** [comment]
Thank you for reply and support.
