### ISSUE TITLE
shock-wave noise  in the begining of the reconstructed audio

### ISSUE THREAD

**Issue by chenyi0818** [google/lyra#46]
Hi, when I use the decoder to reconstrute the audio, I found  a "boom"  problem at the beginning of the reconstructed audio.
![image](https://user-images.githubusercontent.com/37773462/122637034-11566c80-d11f-11eb-923d-c47caa54c69d.png)

**Comment by aluebs** [comment]
Thank you for your report. We are aware of this noise burst at the beginning of output audio and are working on a solution.

**Comment by yassinetoumi18798** [comment]
hi @chenyi0818,

can you tell me please what audio did you use ?

Thank you.

**Comment by chenyi0818** [comment]
hi, thank you for your attention, I use the sub-test-dateset  "test-clean"
in librispeech,  I randomly selected 200 sentences for the test,  the same
problem occurs with every  reconstructed audio. I didn't change the code,
and i follow the process you mentioned .

TOUMI Yassine ***@***.***> 于2021年6月27日周日 上午8:58写道：

**Comment by aluebs** [comment]
This should be fixed in the new [Lyra v0.0.2](https://github.com/google/lyra/releases/tag/v0.0.2).
