### ISSUE TITLE
Could release the Android so library?

### ISSUE THREAD

**Issue by onexuan** [google/lyra#57]
Could release the Android so library? Unable to compile it on MAC

**Comment by aluebs** [comment]
Could you give us a bit more information? What error are you seeing? Do the workarounds in #7 work?

**Comment by onexuan** [comment]
I mean you build and release android armv7 and arm64 so libs to https://github.com/google/lyra/tags, Because I failed to compile on Mac, I can't find the android armv7 and arm64 library

**Comment by aluebs** [comment]
At this point we are not planning on releasing the Android so libraries, but we can try to help you build them yourself.
