### ISSUE TITLE
use of undeclared identifier 'prefix_len'

### ISSUE THREAD

**Issue by zhangjiemin000** [google/lyra#58]
Hi,i used 
```
"bazel build android_example:lyra_android_example --config=android_arm64 --copt=-DBENCHMARK" 
```
to build apk for Android,  but failed with following error:
```
external/com_google_glog/src/logging.cc:798:35: error: use of undeclared identifier 'prefix_len'
                        message + prefix_len);
                                  ^
1 error generated.
```
my bazel vesion is 4.0.0, and my system version is MacOS 11.3.1 .

could you help me? thank you

**Comment by aluebs** [comment]
This seems like an unrelated error in the logging library. Hopefully this should be fixed there, but you can also try to change the branch or add a tag to our import of the git repository in our [WORKSPACE file](https://github.com/google/lyra/blob/main/WORKSPACE#L93).

**Comment by zhangjiemin000** [comment]
thank you,
i changed the ```com_google_glog``` repository from ```branch = "master" ``` to ``` tag = "v0.4.0" ```.
the problem has been solved.
