### ISSUE TITLE
bazel build -c opt :encoder_main  error  on 16.04.1-Ubuntu x86_64 

### ISSUE THREAD

**Issue by leichaowen** [google/lyra#60]
when use bazel build -c opt :encoder_main, some error has occur

external/com_google_absl/absl/strings/str_cat.h: In function 'chromemedia::absl::lts_2020_09_23::strings_internal::AlphaNumBuffer<16ul> chromemedia::absl::lts_2020_09_23::SixDigits(double)':
external/com_google_absl/absl/strings/str_cat.h:401:64: error: 'struct chromemedia::absl::lts_2020_09_23::strings_internal::AlphaNumBuffer<16ul>' has no member named 'data'
   result.size = numbers_internal::SixDigitsToBuffer(d, &result.data[0]);
                                                                ^
wav_util.cc: At global scope:
wav_util.cc:22:22: error: expected '{' before '::' token
 namespace chromemedia::codec {
                      ^
wav_util.cc:22:24: error: 'codec' in namespace '::' does not name a type
 namespace chromemedia::codec {
                        ^
wav_util.cc:56:1: error: expected '}' at end of input
 }  // namespace chromemedia::codec
 ^
wav_util.cc:56:1: error: expected '}' at end of input
Target //:encoder_main failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.016s, Critical Path: 1.85s
INFO: 13 processes: 13 internal.
FAILED: Build did NOT complete successfully

**Comment by aluebs** [comment]
This seems to be an error in the absl strings library. Hopefully it will be resolved upstream soon, but you can also try to set a different branch or tag in our [WORKSPACE](https://github.com/google/lyra/blob/main/WORKSPACE#L36) file.

**Comment by mchinen** [comment]
We now set a specific tag for absl in WORKSPACE where this issue no longer occurs.
