### ISSUE TITLE
Weight of the file

### ISSUE THREAD

**Issue by rdhp330** [google/lyra#65]
Maybe I'm getting a bit confused about the use of Lyra, but I see that the files generated by the codec are not inferior (in weight) to the original ones.
Doesn't it work in a similar way to .amr which allows you to reduce the weight of the file so it improves the transfer?

**Comment by aluebs** [comment]
Just to make sure we are on the same page, the decoded wav file is still a wav file, so the weight depends on the specific format and sample rate, but not on Lyra. The compression goes from the initial wav file to the ".lyra" file after the encoder. This latter one is what would be stored or sent over the network to be decoded on the other side.
If you still see no compression in that case, please give us more information so we look into it.

**Comment by rdhp330** [comment]
Ok it was my problem. Thank u!
