### ISSUE TITLE
"cannot find Foundation" error for Android example

### ISSUE THREAD

**Issue by hitrefresh** [google/lyra#7]
System Information:
MacOS: 10.15.7
bazel 4.0.0-homebrew
ANDROID_NDK_HOME=$HOME/android/sdk/ndk/21.4.7075529
ANDROID_HOME=$HOME/android/sdk
Python 3.8.3
Apple clang version 12.0.0 (clang-1200.0.31.1), Target: x86_64-apple-darwin19.6.0
javac 1.8.0_181

external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot find Foundation: No such file or directory
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //android_example:lyra_android_example failed to build

**Comment by aluebs** [comment]
Thank you for your detailed report. Currently we only support building for Linux and Android.

**Comment by hitrefresh** [comment]
This was building the Android example, but does that have to be done on a Linux machine?

**Comment by aluebs** [comment]
Currently, a Linux machine es necessary to build the Android example, but maybe @mchinen can comment on building on Mac.

**Comment by mchinen** [comment]
As @aluebs mentioned we officially only support linux development machines, but in theory a mac should be able to build, and it's probably not too hard to get experimental support for android builds on mac.  

I'm not sure when we'll get to look deeper into this but I took a peek.  In case you or others want to dive in, the issue you are running into appears to link in the mac Foundation framework into an android target for some reason, likely due to the (external) abseil project incorrectly setting up mac deps.   
It is probably related to https://github.com/tensorflow/tensorflow/issues/31190
and 
https://github.com/abseil/abseil-cpp/issues/326

The ideal fix is likely in the abseil repo, but a local workaround is described in those issues.

**Comment by a-rose** [comment]
For what it's worth, I was able to build on MacOS using Debian in Docker (Dockerfile here: https://github.com/google/lyra/issues/10#issuecomment-816590476)

**Comment by unknownkid** [comment]
Using the hack method in https://github.com/tensorflow/tensorflow/issues/31190, Lyra can be build on MacOS.
1. run the compile command: "bazel build....", it will failed as above, and the Build.bazel files (2 files) wii be created in Lyra folder.
2. commented the code blocks below in 2 Build.bazel files
# Block 01
# config_setting(
#     name = "osx",
#     constraint_values = [
#         "@bazel_tools//platforms:osx",
#     ],
# )
#
# config_setting(
#     name = "ios",
#     constraint_values = [
#         "@bazel_tools//platforms:ios",
#     ],
# )
# Block 02
    # linkopts = select({
    #     ":osx": [
    #         "-framework Foundation",
    #     ],
    #     ":ios": [
    #         "-framework Foundation",
    #     ],
    #     "//conditions:default": [],
    # }),
3. And run the compile command again, it work.

**Comment by aigeek** [comment]
> Using the hack method in [tensorflow/tensorflow#31190](https://github.com/tensorflow/tensorflow/issues/31190), Lyra can be build on MacOS.
> 
> 1. run the compile command: "bazel build....", it will failed as above, and the Build.bazel files (2 files) wii be created in Lyra folder.
> 2. commented the code blocks below in 2 Build.bazel files:
> 
> # Block 01
> ```
> # config_setting(
> #     name = "osx",
> #     constraint_values = [
> #         "@bazel_tools//platforms:osx",
> #     ],
> # )
> #
> # config_setting(
> #     name = "ios",
> #     constraint_values = [
> #         "@bazel_tools//platforms:ios",
> #     ],
> # )
> ```
> 
> ...
> 
> # Block 02
> ```
> # linkopts = select({
> #     ":osx": [
> #         "-framework Foundation",
> #     ],
> #     ":ios": [
> #         "-framework Foundation",
> #     ],
> #     "//conditions:default": [],
> # }),
> ```
> 
> 1. And run the compile command again, it work.

Hi,I Can not find " the Build.bazel files (2 files) wii be created in Lyra folder":

➜  lyra git:(main) ✗ ls
BUILD                                           external                                        no_op_preprocessor_test.cc
CONTRIBUTING.md                                 feature_extractor_interface.h                   noise_estimator.cc
Doxyfile                                        filter_banks.cc                                 noise_estimator.h
LICENSE                                         filter_banks.h                                  noise_estimator_interface.h
README.md                                       filter_banks_interface.h                        noise_estimator_test.cc
WORKSPACE                                       filter_banks_test.cc                            packet.h
WORKSPACE.bak                                   generative_model_interface.h                    packet_interface.h
android_example                                 gilbert_model.cc                                packet_loss_handler.cc
architecture_utils.h                            gilbert_model.h                                 packet_loss_handler.h
bazel-bin                                       gilbert_model_test.cc                           packet_loss_handler_interface.h
bazel-lyra                                      layer_wrapper.h                                 packet_loss_handler_test.cc
bazel-out                                       layer_wrapper_interface.h                       packet_test.cc
bazel-testlogs                                  layer_wrapper_test_common.h                     preprocessor_interface.h
benchmark_decode.cc                             layer_wrappers_lib.h                            project_and_sample.h
benchmark_decode_lib.cc                         lib                                             project_and_sample_test.cc
benchmark_decode_lib.h                          log_mel_spectrogram_extractor_impl.cc           quadrature_mirror_filter.cc
buffer_merger.cc                                log_mel_spectrogram_extractor_impl.h            quadrature_mirror_filter.h
buffer_merger.h                                 log_mel_spectrogram_extractor_impl_benchmark.cc quadrature_mirror_filter_test.cc
buffer_merger_test.cc                           log_mel_spectrogram_extractor_impl_test.cc      resampler.cc
causal_convolutional_conditioning.h             lyra_components.cc                              resampler.h
causal_convolutional_conditioning_test.cc       lyra_components.h                               resampler_interface.h
comfort_noise_generator.cc                      lyra_config.cc                                  resampler_test.cc
comfort_noise_generator.h                       lyra_config.h                                   sparse_inference_matrixvector.h
comfort_noise_generator_test.cc                 lyra_config.proto                               sparse_inference_matrixvector_test.cc
conv1d_layer_wrapper.h                          lyra_config_test.cc                             spectrogram_predictor_interface.h
conv1d_layer_wrapper_test.cc                    lyra_decoder.cc                                 testdata
decoder_main.cc                                 lyra_decoder.h                                  testing
decoder_main_lib.cc                             lyra_decoder_interface.h                        toolchain
decoder_main_lib.h                              lyra_decoder_test.cc                            transpose_convolutional_layer_wrapper.h
decoder_main_lib_test.cc                        lyra_encoder.cc                                 transpose_convolutional_layer_wrapper_test.cc
denoiser_interface.h                            lyra_encoder.h                                  vector_quantizer_impl.cc
dilated_convolutional_layer_wrapper.h           lyra_encoder_interface.h                        vector_quantizer_impl.h
dilated_convolutional_layer_wrapper_test.cc     lyra_encoder_test.cc                            vector_quantizer_impl_test.cc
dsp_util.cc                                     lyra_integration_test.cc                        vector_quantizer_interface.h
dsp_util.h                                      lyra_types.h                                    wav_util.cc
dsp_util_test.cc                                lyra_wavegru.h                                  wav_util.h
encoder_main.cc                                 lyra_wavegru_test.cc                            wav_util_test.cc
encoder_main_lib.cc                             naive_spectrogram_predictor.cc                  wavegru
encoder_main_lib.h                              naive_spectrogram_predictor.h                   wavegru_model_impl.cc
encoder_main_lib_test.cc                        naive_spectrogram_predictor_test.cc             wavegru_model_impl.h
exported_layers_test.h                          no_op_preprocessor.h                            wavegru_model_impl_test.cc

**Comment by wikipedia2008** [comment]
> > Using the hack method in [tensorflow/tensorflow#31190](https://github.com/tensorflow/tensorflow/issues/31190), Lyra can be build on MacOS.
> > 
> > 1. run the compile command: "bazel build....", it will failed as above, and the Build.bazel files (2 files) wii be created in Lyra folder.
> > 2. commented the code blocks below in 2 Build.bazel files:
> > 
> > # Block 01
> > ```
> > # config_setting(
> > #     name = "osx",
> > #     constraint_values = [
> > #         "@bazel_tools//platforms:osx",
> > #     ],
> > # )
> > #
> > # config_setting(
> > #     name = "ios",
> > #     constraint_values = [
> > #         "@bazel_tools//platforms:ios",
> > #     ],
> > # )
> > ```
> > 
> > 
> > ...
> > # Block 02
> > ```
> > # linkopts = select({
> > #     ":osx": [
> > #         "-framework Foundation",
> > #     ],
> > #     ":ios": [
> > #         "-framework Foundation",
> > #     ],
> > #     "//conditions:default": [],
> > # }),
> > ```
> > 
> > 
> > 
> > 1. And run the compile command again, it work.
> 
> Hi,Thanks,but I Can not find " the Build.bazel files (2 files) wii be created in Lyra folder":
> @ unknownkid @aluebs
> Is it in this folder?
> 
> ➜ lyra git:(main) ✗ ls
> BUILD external no_op_preprocessor_test.cc
> CONTRIBUTING.md feature_extractor_interface.h noise_estimator.cc
> Doxyfile filter_banks.cc noise_estimator.h
> LICENSE filter_banks.h noise_estimator_interface.h
> README.md filter_banks_interface.h noise_estimator_test.cc
> WORKSPACE filter_banks_test.cc packet.h
> WORKSPACE.bak generative_model_interface.h packet_interface.h
> android_example gilbert_model.cc packet_loss_handler.cc
> architecture_utils.h gilbert_model.h packet_loss_handler.h
> bazel-bin gilbert_model_test.cc packet_loss_handler_interface.h
> bazel-lyra layer_wrapper.h packet_loss_handler_test.cc
> bazel-out layer_wrapper_interface.h packet_test.cc
> bazel-testlogs layer_wrapper_test_common.h preprocessor_interface.h
> benchmark_decode.cc layer_wrappers_lib.h project_and_sample.h
> benchmark_decode_lib.cc lib project_and_sample_test.cc
> benchmark_decode_lib.h log_mel_spectrogram_extractor_impl.cc quadrature_mirror_filter.cc
> buffer_merger.cc log_mel_spectrogram_extractor_impl.h quadrature_mirror_filter.h
> buffer_merger.h log_mel_spectrogram_extractor_impl_benchmark.cc quadrature_mirror_filter_test.cc
> buffer_merger_test.cc log_mel_spectrogram_extractor_impl_test.cc resampler.cc
> causal_convolutional_conditioning.h lyra_components.cc resampler.h
> causal_convolutional_conditioning_test.cc lyra_components.h resampler_interface.h
> comfort_noise_generator.cc lyra_config.cc resampler_test.cc
> comfort_noise_generator.h lyra_config.h sparse_inference_matrixvector.h
> comfort_noise_generator_test.cc lyra_config.proto sparse_inference_matrixvector_test.cc
> conv1d_layer_wrapper.h lyra_config_test.cc spectrogram_predictor_interface.h
> conv1d_layer_wrapper_test.cc lyra_decoder.cc testdata
> decoder_main.cc lyra_decoder.h testing
> decoder_main_lib.cc lyra_decoder_interface.h toolchain
> decoder_main_lib.h lyra_decoder_test.cc transpose_convolutional_layer_wrapper.h
> decoder_main_lib_test.cc lyra_encoder.cc transpose_convolutional_layer_wrapper_test.cc
> denoiser_interface.h lyra_encoder.h vector_quantizer_impl.cc
> dilated_convolutional_layer_wrapper.h lyra_encoder_interface.h vector_quantizer_impl.h
> dilated_convolutional_layer_wrapper_test.cc lyra_encoder_test.cc vector_quantizer_impl_test.cc
> dsp_util.cc lyra_integration_test.cc vector_quantizer_interface.h
> dsp_util.h lyra_types.h wav_util.cc
> dsp_util_test.cc lyra_wavegru.h wav_util.h
> encoder_main.cc lyra_wavegru_test.cc wav_util_test.cc
> encoder_main_lib.cc naive_spectrogram_predictor.cc wavegru
> encoder_main_lib.h naive_spectrogram_predictor.h wavegru_model_impl.cc
> encoder_main_lib_test.cc naive_spectrogram_predictor_test.cc wavegru_model_impl.h
> exported_layers_test.h no_op_preprocessor.h wavegru_model_impl_test.cc

bazel-lyra/external/com_google_absl/absl/time/internal/cctz/BUILD.bazel

**Comment by qingkouwei** [comment]
> > Using the hack method in [tensorflow/tensorflow#31190](https://github.com/tensorflow/tensorflow/issues/31190), Lyra can be build on MacOS.
> > 
> > 1. run the compile command: "bazel build....", it will failed as above, and the Build.bazel files (2 files) wii be created in Lyra folder.
> > 2. commented the code blocks below in 2 Build.bazel files:
> > 
> > # Block 01
> > ```
> > # config_setting(
> > #     name = "osx",
> > #     constraint_values = [
> > #         "@bazel_tools//platforms:osx",
> > #     ],
> > # )
> > #
> > # config_setting(
> > #     name = "ios",
> > #     constraint_values = [
> > #         "@bazel_tools//platforms:ios",
> > #     ],
> > # )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ...
> > # Block 02
> > ```
> > # linkopts = select({
> > #     ":osx": [
> > #         "-framework Foundation",
> > #     ],
> > #     ":ios": [
> > #         "-framework Foundation",
> > #     ],
> > #     "//conditions:default": [],
> > # }),
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 1. And run the compile command again, it work.
> 
> Hi,Thanks,but I Can not find " the Build.bazel files (2 files) wii be created in Lyra folder":
> @ unknownkid @aluebs
> Is it in this folder?
> 
> ➜ lyra git:(main) ✗ ls
> BUILD external no_op_preprocessor_test.cc
> CONTRIBUTING.md feature_extractor_interface.h noise_estimator.cc
> Doxyfile filter_banks.cc noise_estimator.h
> LICENSE filter_banks.h noise_estimator_interface.h
> README.md filter_banks_interface.h noise_estimator_test.cc
> WORKSPACE filter_banks_test.cc packet.h
> WORKSPACE.bak generative_model_interface.h packet_interface.h
> android_example gilbert_model.cc packet_loss_handler.cc
> architecture_utils.h gilbert_model.h packet_loss_handler.h
> bazel-bin gilbert_model_test.cc packet_loss_handler_interface.h
> bazel-lyra layer_wrapper.h packet_loss_handler_test.cc
> bazel-out layer_wrapper_interface.h packet_test.cc
> bazel-testlogs layer_wrapper_test_common.h preprocessor_interface.h
> benchmark_decode.cc layer_wrappers_lib.h project_and_sample.h
> benchmark_decode_lib.cc lib project_and_sample_test.cc
> benchmark_decode_lib.h log_mel_spectrogram_extractor_impl.cc quadrature_mirror_filter.cc
> buffer_merger.cc log_mel_spectrogram_extractor_impl.h quadrature_mirror_filter.h
> buffer_merger.h log_mel_spectrogram_extractor_impl_benchmark.cc quadrature_mirror_filter_test.cc
> buffer_merger_test.cc log_mel_spectrogram_extractor_impl_test.cc resampler.cc
> causal_convolutional_conditioning.h lyra_components.cc resampler.h
> causal_convolutional_conditioning_test.cc lyra_components.h resampler_interface.h
> comfort_noise_generator.cc lyra_config.cc resampler_test.cc
> comfort_noise_generator.h lyra_config.h sparse_inference_matrixvector.h
> comfort_noise_generator_test.cc lyra_config.proto sparse_inference_matrixvector_test.cc
> conv1d_layer_wrapper.h lyra_config_test.cc spectrogram_predictor_interface.h
> conv1d_layer_wrapper_test.cc lyra_decoder.cc testdata
> decoder_main.cc lyra_decoder.h testing
> decoder_main_lib.cc lyra_decoder_interface.h toolchain
> decoder_main_lib.h lyra_decoder_test.cc transpose_convolutional_layer_wrapper.h
> decoder_main_lib_test.cc lyra_encoder.cc transpose_convolutional_layer_wrapper_test.cc
> denoiser_interface.h lyra_encoder.h vector_quantizer_impl.cc
> dilated_convolutional_layer_wrapper.h lyra_encoder_interface.h vector_quantizer_impl.h
> dilated_convolutional_layer_wrapper_test.cc lyra_encoder_test.cc vector_quantizer_impl_test.cc
> dsp_util.cc lyra_integration_test.cc vector_quantizer_interface.h
> dsp_util.h lyra_types.h wav_util.cc
> dsp_util_test.cc lyra_wavegru.h wav_util.h
> encoder_main.cc lyra_wavegru_test.cc wav_util_test.cc
> encoder_main_lib.cc naive_spectrogram_predictor.cc wavegru
> encoder_main_lib.h naive_spectrogram_predictor.h wavegru_model_impl.cc
> encoder_main_lib_test.cc naive_spectrogram_predictor_test.cc wavegru_model_impl.h
> exported_layers_test.h no_op_preprocessor.h wavegru_model_impl_test.cc

bazel-lyra/external/com_google_absl/absl/time/internal/cctz/BUILD.bazel and bazel-lyra/external/com_google_absl/absl/BUILD.bazel

**Comment by aluebs** [comment]
The new [Lyra 1.2.0](https://github.com/google/lyra/releases/tag/v1.2.0) release has experimental Mac support. So hopefully this should be fixed now.
