### ISSUE TITLE
Lyra fails to build in latest GitHub Actions virtual environment

### ISSUE THREAD

**Issue by reekystive** [google/lyra#76]
In the `ubuntu-latest` and `macos-latest` virtual environments, the default Bazel version is `5.0.0`, which requires `build-tools 30.0.0` or newer version to work properly. Lyra is currently using `build-tools 29.0.3`, which will cause Lyra failed to build with the default Bazel in GitHub Actions virtual environments.

After my attempts, I successfully built Lyra with:

- `Bazel 5.0.0`
- `build-tools 30.0.3`
- `platforms android-30`
- `ndk 21.4.7075529`

Built successfully on hosts:

- `Ubuntu 20.04 (amd64)`
  - `linux-bin ✅`
  - `android-bin ✅`
  - `android-app ✅`
- `macOS 11 (Intel)`
  - `macos-bin ✅`
  - `android-bin ❌`
  - `android-app ❌`
- `macOS 12.2 (Apple Silicon)`
  - `macos-bin ✅`
  - `android-bin ❌`
  - `android-app ❌`

**Comment by reekystive** [comment]
#78 fixes this.

**Comment by aluebs** [comment]
Thank you for testing and fixing this :)
