### ISSUE TITLE
Compiling using Bazel Emscripten toolchain

### ISSUE THREAD

**Issue by kang18732** [google/lyra#80]
I am currently attempting to compile LYRA into web assembly using the Bazel Emscripten toolchain.  
  https://github.com/emscripten-core/emsdk/tree/main/bazel          

However, it keeps on emitting "Build did NOT complete successfully." and fails to compile.
Is there something I am missing here, or is LYRA simply impossible to convert to web assembly at the moment?

**Comment by aluebs** [comment]
I have never used that toolchain, or try to port Lyra to WASM, but I know there are some issues with it. Maybe you can find some pointers in #49?
