### ISSUE TITLE
Failed to build for linux

### ISSUE THREAD

**Issue by Ryuk17** [google/lyra#85]
I try to build lyra for linux with `bazel build -c opt :encoder_main`, while I met the following error, which seems that the Android NDK is necessary.
![2022-08-09 12-51-24 的屏幕截图](https://user-images.githubusercontent.com/22525811/183567118-1e50d6af-ae3a-43fc-863b-384bff9da472.png)
 
If I just want to build and run lyra on linux, is it necessary to download  Android NDK ?

**Comment by aluebs** [comment]
Unfortunately at this time, the Android NDK is necessary even to build Lyra for Linux. But a completely agree that it shouldn't. We'll be looking into it, but if you figure it out, patches are always welcome :)

**Comment by Ryuk17** [comment]
Thanks for you reply, I am willing to find some methods to build Lyra for Linux without Android NDK.

**Comment by aluebs** [comment]
This will be fixed in the next release, but in the meantime, as a workaround, you can remove the android_sdk_repository and android_ndk_repository from the [WORKSPACE](https://github.com/google/lyra/blob/main/WORKSPACE#L118-L127).

**Comment by aluebs** [comment]
This was fixed with the [Lyra 1.2.0](https://github.com/google/lyra/releases/tag/v1.2.0) release.
