### ISSUE TITLE
Realtime Encoding and Decoding on Linux Qstn!

### ISSUE THREAD

**Issue by thesunRider** [google/lyra#86]
Kudos,
_Great Work!_

I wish to capture the microphone stream and feed it to _Lyra_ instead of supplying a wav file,The objective is to create  Underwater Communication Equipment. So how should I go on about feeding the binary stream to _Lyra_ for encoding it **realtime**, The API's mentioned in the docs seem to all accept filename as input.The target is **LINUX**.

Regards.

**Comment by aluebs** [comment]
Thank you for the question. That is a great application for Lyra. If you are writing a C++ Linux application, you can use the [LyraEncoder](https://github.com/google/lyra/blob/main/lyra_encoder.h) and [LyraDecoder](https://github.com/google/lyra/blob/main/lyra_decoder.h) APIs described in the API section of the [README](https://github.com/google/lyra/blob/main/README.md), which run in real-time and encode and decode packets of 40ms. For an example on how to do that, you can refer to the [android_example](https://github.com/google/lyra/tree/main/android_example), [encoder_main](https://github.com/google/lyra/blob/main/encoder_main_lib.cc#L79) and [decoder_main](https://github.com/google/lyra/blob/main/decoder_main_lib.cc#L79), or the [lyra_integration_test](https://github.com/google/lyra/blob/main/lyra_integration_test.cc#L98).
