### ISSUE TITLE
What is the packet structure for  the encoded ".lyra" file ?

### ISSUE THREAD

**Issue by zxinhui-fb** [google/lyra#97]
Is there any packet structure in the ".lyra' file ?  
by looking at the source code, it seems the '.lyra' file only consists of bit stream byte by byte without any internal structure.

https://github.com/google/lyra/blob/main/encoder_main_lib.cc#L87

**Comment by aluebs** [comment]
That is correct. Currently the Lyra packet has no internal structure and only contains the bits from the quantization model. That is because, as is, we don't need any additional information to be sent over, and haven't committed to a stable bitstream yet to maintain development flexibility.

**Comment by zxinhui-fb** [comment]
thanks!
