### ISSUE TITLE
Lyra + Gstreamer + webRTC - missing specs?

### ISSUE THREAD

**Issue by rocco-haro** [google/lyra#98]
Hi folks, first of all thanks for shipping version 2! So stoked on this work. 

We're looking to explore integrating lyra into a gstreamer pipeline that is stacked with webRTC. I'm not the webRTC expert on our team, but my contacts are mentioning they had trouble finding the required specs in order to get started on building such an integration. 

They mentioned RTP payloading/depayloading, and perhaps there are other items/specs needed to be understood  before embarking on this journey. 

We would greatly appreciate some guidance :)

**Comment by rocco-haro** [comment]
Wicked fast response, thanks for the clarification @aluebs! 

Do you think we could get a RTP spec, and in return we could open source the custom implementation through the gstreamer community? We're working with the folks over at Centricular: https://www.centricular.com/about/

**Comment by rocco-haro** [comment]
@aluebs i've come to learn that we actually won't be able to incorporate lyra into our project since we are purely web browser based at the moment. Thank you for the consideration!

**Comment by aluebs** [comment]
Thank you for letting us know.
